### ISSUE TITLE
Can't install with pip in python 3.12

### ISSUE THREAD

**Issue by cdegut** [idptools/afrc#1]
when trying to install afrc in python 3.12 via pip i get this error:
googling the issue suggest that versioneer.py, is not compatible with latest python, what is the recomanded python to use?

` >pip install afrc
Collecting afrc
  Using cached afrc-0.3.4.tar.gz (58 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      C:\Users\Clement\AppData\Local\Temp\pip-install-uq_z1jx6\afrc_2a3816ed4bc04f148793d541f21df6ab\versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "C:\Users\Clement\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Clement\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Clement\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Clement\AppData\Local\Temp\pip-build-env-epsh4x4x\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Clement\AppData\Local\Temp\pip-build-env-epsh4x4x\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Clement\AppData\Local\Temp\pip-build-env-epsh4x4x\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Clement\AppData\Local\Temp\pip-build-env-epsh4x4x\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 30, in <module>
        File "C:\Users\Clement\AppData\Local\Temp\pip-install-uq_z1jx6\afrc_2a3816ed4bc04f148793d541f21df6ab\versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\Clement\AppData\Local\Temp\pip-install-uq_z1jx6\afrc_2a3816ed4bc04f148793d541f21df6ab\versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Clement\AppData\Local\Temp\pip-install-uq_z1jx6\afrc_2a3816ed4bc04f148793d541f21df6ab\versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by alexholehouse** [comment]
Yeah - my apologies; this is a known issue. The version of versioneer (the tool we use for version control) is unfortunately not maintained past 3.11. This summer (July) we are planning to update our versioning to accommodate this for our relevant packages which will be a long and tedious job. For now the easiest workaround is to create an environment with python 3.11; sorry for this inconvenience, but we are I hope merely weeks from a fix here!

**Comment by alexholehouse** [comment]
The other option may be (depending on your use case) [to use our Google colab version](https://colab.research.google.com/drive/1WHw8ous7IgcKd2LKYuJLeBTlkdEYoRAk?usp=sharing)

**Comment by cdegut** [comment]
> The other option may be (depending on your use case) [to use our Google colab version](https://colab.research.google.com/drive/1WHw8ous7IgcKd2LKYuJLeBTlkdEYoRAk?usp=sharing)

I am afraid the google collab contain some matplolib errors:

`Chain length: 139 residues
Average AFRC end-to-end distance : 69.14 Å

Error in callback <function _draw_all_if_interactive at 0x7b2ec7d1bd90> (for post_execute):

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

[/usr/local/lib/python3.10/dist-packages/matplotlib/pyplot.py](https://localhost:8080/#) in _draw_all_if_interactive()
    118 def _draw_all_if_interactive():
    119     if matplotlib.is_interactive():
--> 120         draw_all()
    121 
    122 

18 frames

[/usr/local/lib/python3.10/dist-packages/matplotlib/_mathtext.py](https://localhost:8080/#) in parse(self, s, fonts_object, fontsize, dpi)
   1993         except ParseBaseException as err:
   1994             # explain becomes a plain method on pyparsing 3 (err.explain(0)).
-> 1995             raise ValueError("\n" + ParseException.explain(err, 0)) from None
   1996         self._state_stack = None
   1997         self._in_subscript_or_superscript = False

ValueError: 
\rmR_e
^
ParseFatalException: Expected token, found '\'  (at char 0), (line:1, col:1)

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

[/usr/local/lib/python3.10/dist-packages/IPython/core/formatters.py](https://localhost:8080/#) in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

18 frames

[/usr/local/lib/python3.10/dist-packages/matplotlib/_mathtext.py](https://localhost:8080/#) in parse(self, s, fonts_object, fontsize, dpi)
   1993         except ParseBaseException as err:
   1994             # explain becomes a plain method on pyparsing 3 (err.explain(0)).
-> 1995             raise ValueError("\n" + ParseException.explain(err, 0)) from None
   1996         self._state_stack = None
   1997         self._in_subscript_or_superscript = False

ValueError: 
\rmR_e
^
ParseFatalException: Expected token, found '\'  (at char 0), (line:1, col:1)

<Figure size 770x350 with 1 Axes>`

**Comment by ryanemenecker** [comment]
To follow up, the Github version of afrc should now support newer versions of Python as we have updated it to use pyproject.toml for install. We will shortly update the PyPi version!
-Ryan
